name              'nginx'
maintainer        'Mike Fiedler'
maintainer_email  'miketheman@gmail.com'
license           'Apache 2.0'
description       'Installs and configures nginx'
issues_url        'https://github.com/miketheman/nginx/issues'
source_url        'https://github.com/miketheman/nginx'
version           '2.99.1'

depends 'ohai',   '~> 4.0.0'
